// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ping.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingResponse struct {
	Url                  string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Date                 *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51d96c3ad891f5, []int{0}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *PingResponse) GetDate() *timestamppb.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d51d96c3ad891f5, []int{1}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PingResponse)(nil), "pingProto.pingResponse")
	proto.RegisterType((*PingRequest)(nil), "pingProto.pingRequest")
}

func init() {
	proto.RegisterFile("ping.proto", fileDescriptor_6d51d96c3ad891f5)
}

var fileDescriptor_6d51d96c3ad891f5 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xc8, 0xcc, 0x4b,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0xb1, 0x03, 0x40, 0x4c, 0x29, 0xf9, 0xf4,
	0xfc, 0xfc, 0xf4, 0x9c, 0x54, 0x7d, 0xb0, 0x44, 0x52, 0x69, 0x9a, 0x7e, 0x49, 0x66, 0x6e, 0x6a,
	0x71, 0x49, 0x62, 0x6e, 0x01, 0x44, 0xad, 0x52, 0x00, 0x17, 0x0f, 0x48, 0x75, 0x50, 0x6a, 0x71,
	0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x00, 0x17, 0x73, 0x69, 0x51, 0x8e, 0x04, 0xa3, 0x02, 0xa3,
	0x06, 0x67, 0x10, 0x88, 0x29, 0xa4, 0xc7, 0xc5, 0x92, 0x92, 0x58, 0x92, 0x2a, 0xc1, 0xa4, 0xc0,
	0xa8, 0xc1, 0x6d, 0x24, 0xa5, 0x07, 0x31, 0x51, 0x0f, 0x66, 0xa2, 0x5e, 0x08, 0xcc, 0xc4, 0x20,
	0xb0, 0x3a, 0x25, 0x5e, 0x2e, 0x6e, 0x88, 0x89, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x46, 0xde, 0x5c,
	0xdc, 0x1e, 0xa9, 0x89, 0x39, 0x25, 0x19, 0xc9, 0x19, 0xa9, 0xc9, 0xd9, 0x42, 0x36, 0x5c, 0xec,
	0xee, 0xa9, 0x25, 0x01, 0x99, 0x79, 0xe9, 0x42, 0x62, 0x7a, 0x70, 0x77, 0xea, 0x21, 0xe9, 0x90,
	0x12, 0xc7, 0x10, 0x87, 0xb8, 0x4d, 0x89, 0xc1, 0x89, 0x3f, 0x8a, 0xb7, 0x24, 0x3f, 0x3d, 0x1f,
	0xe2, 0x1d, 0xeb, 0x82, 0xa4, 0x24, 0x36, 0x30, 0xcb, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x04,
	0x2e, 0x57, 0x4b, 0xff, 0x00, 0x00, 0x00,
}
