// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Interface exported by the server.
type User struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	LimitPerDay          int64                  `protobuf:"varint,3,opt,name=limit_per_day,json=limitPerDay,proto3" json:"limit_per_day,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetLimitPerDay() int64 {
	if m != nil {
		return m.LimitPerDay
	}
	return 0
}

func (m *User) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type GetAllUsersReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllUsersReq) Reset()         { *m = GetAllUsersReq{} }
func (m *GetAllUsersReq) String() string { return proto.CompactTextString(m) }
func (*GetAllUsersReq) ProtoMessage()    {}
func (*GetAllUsersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *GetAllUsersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllUsersReq.Unmarshal(m, b)
}
func (m *GetAllUsersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllUsersReq.Marshal(b, m, deterministic)
}
func (m *GetAllUsersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllUsersReq.Merge(m, src)
}
func (m *GetAllUsersReq) XXX_Size() int {
	return xxx_messageInfo_GetAllUsersReq.Size(m)
}
func (m *GetAllUsersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllUsersReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllUsersReq proto.InternalMessageInfo

type GetAllUsersRes struct {
	User                 []*User  `protobuf:"bytes,1,rep,name=User,proto3" json:"User,omitempty"`
	TotalUser            int64    `protobuf:"varint,2,opt,name=total_user,json=totalUser,proto3" json:"total_user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllUsersRes) Reset()         { *m = GetAllUsersRes{} }
func (m *GetAllUsersRes) String() string { return proto.CompactTextString(m) }
func (*GetAllUsersRes) ProtoMessage()    {}
func (*GetAllUsersRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *GetAllUsersRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllUsersRes.Unmarshal(m, b)
}
func (m *GetAllUsersRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllUsersRes.Marshal(b, m, deterministic)
}
func (m *GetAllUsersRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllUsersRes.Merge(m, src)
}
func (m *GetAllUsersRes) XXX_Size() int {
	return xxx_messageInfo_GetAllUsersRes.Size(m)
}
func (m *GetAllUsersRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllUsersRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllUsersRes proto.InternalMessageInfo

func (m *GetAllUsersRes) GetUser() []*User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GetAllUsersRes) GetTotalUser() int64 {
	if m != nil {
		return m.TotalUser
	}
	return 0
}

type GetSingleUserReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSingleUserReq) Reset()         { *m = GetSingleUserReq{} }
func (m *GetSingleUserReq) String() string { return proto.CompactTextString(m) }
func (*GetSingleUserReq) ProtoMessage()    {}
func (*GetSingleUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *GetSingleUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSingleUserReq.Unmarshal(m, b)
}
func (m *GetSingleUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSingleUserReq.Marshal(b, m, deterministic)
}
func (m *GetSingleUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSingleUserReq.Merge(m, src)
}
func (m *GetSingleUserReq) XXX_Size() int {
	return xxx_messageInfo_GetSingleUserReq.Size(m)
}
func (m *GetSingleUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSingleUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetSingleUserReq proto.InternalMessageInfo

func (m *GetSingleUserReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetSingleUserRes struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSingleUserRes) Reset()         { *m = GetSingleUserRes{} }
func (m *GetSingleUserRes) String() string { return proto.CompactTextString(m) }
func (*GetSingleUserRes) ProtoMessage()    {}
func (*GetSingleUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *GetSingleUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSingleUserRes.Unmarshal(m, b)
}
func (m *GetSingleUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSingleUserRes.Marshal(b, m, deterministic)
}
func (m *GetSingleUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSingleUserRes.Merge(m, src)
}
func (m *GetSingleUserRes) XXX_Size() int {
	return xxx_messageInfo_GetSingleUserRes.Size(m)
}
func (m *GetSingleUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSingleUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetSingleUserRes proto.InternalMessageInfo

func (m *GetSingleUserRes) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	LimitPerDay          int64    `protobuf:"varint,2,opt,name=limit_per_day,json=limitPerDay,proto3" json:"limit_per_day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserReq) Reset()         { *m = CreateUserReq{} }
func (m *CreateUserReq) String() string { return proto.CompactTextString(m) }
func (*CreateUserReq) ProtoMessage()    {}
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *CreateUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReq.Unmarshal(m, b)
}
func (m *CreateUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReq.Marshal(b, m, deterministic)
}
func (m *CreateUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReq.Merge(m, src)
}
func (m *CreateUserReq) XXX_Size() int {
	return xxx_messageInfo_CreateUserReq.Size(m)
}
func (m *CreateUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReq proto.InternalMessageInfo

func (m *CreateUserReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserReq) GetLimitPerDay() int64 {
	if m != nil {
		return m.LimitPerDay
	}
	return 0
}

type CreateUserRes struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRes) Reset()         { *m = CreateUserRes{} }
func (m *CreateUserRes) String() string { return proto.CompactTextString(m) }
func (*CreateUserRes) ProtoMessage()    {}
func (*CreateUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *CreateUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRes.Unmarshal(m, b)
}
func (m *CreateUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRes.Marshal(b, m, deterministic)
}
func (m *CreateUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRes.Merge(m, src)
}
func (m *CreateUserRes) XXX_Size() int {
	return xxx_messageInfo_CreateUserRes.Size(m)
}
func (m *CreateUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRes proto.InternalMessageInfo

func (m *CreateUserRes) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type EditUserReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditUserReq) Reset()         { *m = EditUserReq{} }
func (m *EditUserReq) String() string { return proto.CompactTextString(m) }
func (*EditUserReq) ProtoMessage()    {}
func (*EditUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *EditUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditUserReq.Unmarshal(m, b)
}
func (m *EditUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditUserReq.Marshal(b, m, deterministic)
}
func (m *EditUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditUserReq.Merge(m, src)
}
func (m *EditUserReq) XXX_Size() int {
	return xxx_messageInfo_EditUserReq.Size(m)
}
func (m *EditUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EditUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_EditUserReq proto.InternalMessageInfo

func (m *EditUserReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type EditUserRes struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditUserRes) Reset()         { *m = EditUserRes{} }
func (m *EditUserRes) String() string { return proto.CompactTextString(m) }
func (*EditUserRes) ProtoMessage()    {}
func (*EditUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *EditUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditUserRes.Unmarshal(m, b)
}
func (m *EditUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditUserRes.Marshal(b, m, deterministic)
}
func (m *EditUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditUserRes.Merge(m, src)
}
func (m *EditUserRes) XXX_Size() int {
	return xxx_messageInfo_EditUserRes.Size(m)
}
func (m *EditUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_EditUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_EditUserRes proto.InternalMessageInfo

func (m *EditUserRes) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserReq) Reset()         { *m = DeleteUserReq{} }
func (m *DeleteUserReq) String() string { return proto.CompactTextString(m) }
func (*DeleteUserReq) ProtoMessage()    {}
func (*DeleteUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *DeleteUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserReq.Unmarshal(m, b)
}
func (m *DeleteUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserReq.Marshal(b, m, deterministic)
}
func (m *DeleteUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserReq.Merge(m, src)
}
func (m *DeleteUserReq) XXX_Size() int {
	return xxx_messageInfo_DeleteUserReq.Size(m)
}
func (m *DeleteUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserReq proto.InternalMessageInfo

func (m *DeleteUserReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type DeleteUserRes struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRes) Reset()         { *m = DeleteUserRes{} }
func (m *DeleteUserRes) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRes) ProtoMessage()    {}
func (*DeleteUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *DeleteUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRes.Unmarshal(m, b)
}
func (m *DeleteUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRes.Marshal(b, m, deterministic)
}
func (m *DeleteUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRes.Merge(m, src)
}
func (m *DeleteUserRes) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRes.Size(m)
}
func (m *DeleteUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRes proto.InternalMessageInfo

func (m *DeleteUserRes) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "todo.User")
	proto.RegisterType((*GetAllUsersReq)(nil), "todo.GetAllUsersReq")
	proto.RegisterType((*GetAllUsersRes)(nil), "todo.GetAllUsersRes")
	proto.RegisterType((*GetSingleUserReq)(nil), "todo.GetSingleUserReq")
	proto.RegisterType((*GetSingleUserRes)(nil), "todo.GetSingleUserRes")
	proto.RegisterType((*CreateUserReq)(nil), "todo.CreateUserReq")
	proto.RegisterType((*CreateUserRes)(nil), "todo.CreateUserRes")
	proto.RegisterType((*EditUserReq)(nil), "todo.EditUserReq")
	proto.RegisterType((*EditUserRes)(nil), "todo.EditUserRes")
	proto.RegisterType((*DeleteUserReq)(nil), "todo.DeleteUserReq")
	proto.RegisterType((*DeleteUserRes)(nil), "todo.DeleteUserRes")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xdf, 0x6a, 0xd4, 0x4e,
	0x18, 0x65, 0x76, 0xf7, 0xd7, 0x5f, 0xf7, 0x0b, 0xa9, 0xdb, 0x51, 0x34, 0x04, 0xd4, 0x25, 0x17,
	0x12, 0x10, 0xb3, 0x12, 0x41, 0x28, 0x5e, 0xc8, 0x6a, 0xa5, 0x78, 0x55, 0x49, 0x15, 0xc1, 0x9b,
	0x90, 0xed, 0x7c, 0x2e, 0x03, 0xd9, 0x4e, 0x3a, 0xf3, 0xad, 0xd0, 0xa7, 0xf0, 0x65, 0x7c, 0x0c,
	0x1f, 0x4a, 0x66, 0xa6, 0xd9, 0x6e, 0xba, 0x0b, 0xb9, 0x9b, 0x39, 0x39, 0xe7, 0xfb, 0x73, 0x4e,
	0x18, 0x80, 0xb5, 0x41, 0x9d, 0x35, 0x5a, 0x91, 0xe2, 0x23, 0x52, 0x42, 0xc5, 0xcf, 0x97, 0x4a,
	0x2d, 0x6b, 0x9c, 0x39, 0x6c, 0xb1, 0xfe, 0x39, 0x23, 0xb9, 0x42, 0x43, 0xd5, 0xaa, 0xf1, 0xb4,
	0xe4, 0x2f, 0x83, 0xd1, 0x37, 0x83, 0x9a, 0x1f, 0xc1, 0x40, 0x8a, 0x88, 0x4d, 0x59, 0x3a, 0x2e,
	0x06, 0x52, 0xf0, 0x18, 0x0e, 0x6d, 0xb5, 0xab, 0x6a, 0x85, 0xd1, 0xc0, 0xa1, 0x9b, 0x3b, 0x4f,
	0x20, 0xac, 0xe5, 0x4a, 0x52, 0xd9, 0xa0, 0x2e, 0x45, 0x75, 0x13, 0x0d, 0xa7, 0x2c, 0x1d, 0x16,
	0x81, 0x03, 0xbf, 0xa0, 0x3e, 0xad, 0x6e, 0xf8, 0x09, 0xc0, 0xa5, 0xc6, 0x8a, 0x50, 0x94, 0x15,
	0x45, 0xa3, 0x29, 0x4b, 0x83, 0x3c, 0xce, 0xfc, 0x38, 0x59, 0x3b, 0x4e, 0xf6, 0xb5, 0x1d, 0xa7,
	0x18, 0xdf, 0xb2, 0xe7, 0x64, 0xa5, 0xeb, 0x46, 0xb4, 0xd2, 0xff, 0xfa, 0xa5, 0xb7, 0xec, 0x39,
	0x25, 0x13, 0x38, 0x3a, 0x43, 0x9a, 0xd7, 0xb5, 0xdd, 0xc9, 0x14, 0x78, 0x9d, 0x9c, 0xdf, 0x43,
	0x0c, 0x7f, 0xe6, 0x37, 0x8e, 0xd8, 0x74, 0x98, 0x06, 0x39, 0x64, 0xd6, 0xa8, 0xcc, 0x22, 0x85,
	0x77, 0xe2, 0x29, 0x00, 0x29, 0xaa, 0xea, 0xd2, 0xee, 0xeb, 0x76, 0x1f, 0x16, 0x63, 0x87, 0xd8,
	0xcf, 0xc9, 0x4b, 0x98, 0x9c, 0x21, 0x5d, 0xc8, 0xab, 0x65, 0x8d, 0x4e, 0x85, 0xd7, 0xfc, 0x09,
	0xfc, 0x6f, 0xc9, 0xe5, 0xc6, 0xc1, 0x03, 0x7b, 0xfd, 0x2c, 0x92, 0x7c, 0x87, 0xec, 0xfa, 0xaf,
	0x7d, 0x7f, 0x76, 0xbf, 0xbf, 0xc5, 0x93, 0x73, 0x08, 0x3f, 0x3a, 0x2f, 0xda, 0xea, 0xdb, 0x51,
	0xb0, 0xbe, 0x28, 0x06, 0x3b, 0x51, 0x24, 0xb3, 0x6e, 0xc1, 0xfe, 0x09, 0x5e, 0x40, 0xf0, 0x49,
	0x48, 0xea, 0xdd, 0xee, 0xd5, 0x36, 0xaf, 0xbf, 0x6c, 0x0a, 0xe1, 0x29, 0xd6, 0x48, 0xfd, 0xb6,
	0xcd, 0xba, 0xcc, 0xde, 0xd2, 0xf9, 0x6f, 0x06, 0xc7, 0x9e, 0x5b, 0x09, 0xd4, 0x17, 0xa8, 0x7f,
	0xc9, 0x4b, 0xe4, 0x27, 0x10, 0x6c, 0x65, 0xcf, 0x1f, 0x79, 0x59, 0xf7, 0x07, 0x89, 0xf7, 0xa1,
	0x86, 0xbf, 0x87, 0xb0, 0x13, 0x1c, 0x7f, 0xbc, 0xa1, 0x75, 0xa2, 0x8f, 0xf7, 0xe3, 0x26, 0xff,
	0xc3, 0x60, 0x62, 0xcf, 0xdf, 0xb5, 0x24, 0x6c, 0x07, 0x7a, 0x0b, 0x70, 0x97, 0x04, 0x7f, 0xe8,
	0xa5, 0x9d, 0xb0, 0xe3, 0x3d, 0xa0, 0xe1, 0xaf, 0xe1, 0xb0, 0x35, 0x9a, 0x1f, 0x7b, 0xc2, 0x56,
	0x40, 0xf1, 0x0e, 0x64, 0x6c, 0xa7, 0x3b, 0x07, 0xdb, 0x4e, 0x1d, 0xf7, 0xe3, 0x3d, 0xa0, 0xf9,
	0xf0, 0xe0, 0x47, 0x48, 0x6a, 0xa9, 0xfc, 0x83, 0xf1, 0xae, 0x59, 0x2c, 0x0e, 0xdc, 0xe9, 0xcd,
	0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x45, 0xb8, 0x93, 0xbc, 0x5c, 0x04, 0x00, 0x00,
}
